apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: store-peer0
  namespace: store-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: store-peer0
  chart:
    git: ssh://git@github.com/vangarasandeep/blockchain-automation-framework.git
    ref: develop
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: store-net
      images:
        couchdb: hyperledger/fabric-couchdb:0.4.18
        peer: hyperledger/fabric-peer:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.store-net:7051
      gossipexternalendpoint: peer0.store-net.org3ambassador.blockchaincloudpoc.com:8443
      localmspid: storeMSP
      loglevel: info
      tlsstatus: true
      couchdb:
        username: store-user

    storage:
      peer:
        storageclassname: storesc
        storagesize: 512Mi
      couchdb:
        storageclassname: storesc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://aedb1188bc7b711eab6f5060b7f7fdf6-993300541.ap-southeast-1.elb.amazonaws.com:9000
      authpath: store-net-auth
      secretprefix: secret/crypto/peerOrganizations/store-net/peers/peer0.store-net
      secretambassador: secret/crypto/peerOrganizations/store-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/store-net/couchdb/store?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: haproxy
      external_url_suffix: org3ambassador.blockchaincloudpoc.com
